### ISSUE TITLE
Admins are given the answers of the qualification form when completing it

### ISSUE THREAD

**Issue by multun** [prologin/concours-site#152]
`<haltode> j'ai fait "enregistrer les nouvelles réponses" et ça m'a affiché les bonnes réponses du QCM :D`
huh my heart é_è

**Comment by zopieux** [comment]
Osef ce sont des admins.

**Comment by Elfikurr** [comment]
Can we close this ?
Or do we have a "real reason" other than "it breaks my heart" ? :DD

**Comment by seirl** [comment]
I think it should be fixed, you want to be able to check easily the QCM workflow even as an admin. It's just not high priority.

**Comment by Elfikurr** [comment]
Do we want a "display correction" button, or do we want to remove this completely ?
The admin can check the correct answers in the django admin, so we could just remove the answers showing on the qualification form ?
(we could also allow the staff to do the qualifications, instead of preventing them by calling `form_invalid` ?)

**Comment by seirl** [comment]
> Do we want a "display correction" button, or do we want to remove this completely ?

I think you should remove the broken feature, and the "display correction" could come afterwards as a separate issue.

> The admin can check the correct answers in the django admin, so we could just remove the answers showing on the qualification form ?
> (we could also allow the staff to do the qualifications, instead of preventing them by calling `form_invalid` ?)

SGTM

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/152
