### ISSUE TITLE
Hide malus during qualifications

### ISSUE THREAD

**Issue by cafehaine** [prologin/concours-site#154]
(but show a warning that during ERs maluses will be counted for each try with an invalid code under the "send code" block)

**Comment by Elfikurr** [comment]
Is this not already the case ?
The malus is shown, but it is said that it is not taken into account, but will be during the semifinals.

**Comment by seirl** [comment]
The reason for this issue is that we get a lot of people asking us to remove their malus for various reasons, and it would be more clear for them to not have that be shown during the qualifications.
But on the other hand, you can't do a ranking if you don't have a malus system, and it's not great to hide a malus that will still count for the website ranking, so I think this should be discussed more before implementation.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/154
