### ISSUE TITLE
Template '*.html.html' does not exist

### ISSUE THREAD

**Issue by alarsyo** [prologin/concours-site#227]
The logs are filled with erros like these:

```
Nov 02 11:02:46 rosa.prologin.org gunicorn[846]: Template 'users/mails/pswd_reset.body.html.html' does not exists.
Nov 02 11:25:09 rosa.prologin.org gunicorn[846]: Template 'users/mails/pswd_reset.body.html.html' does not exists.
Nov 02 11:48:40 rosa.prologin.org gunicorn[846]: Template 'users/mails/activation.body.html.html' does not exists.
Nov 02 12:22:33 rosa.prologin.org gunicorn[846]: Template 'users/mails/activation.body.html.html' does not exists.
```

This happens because `djmail` looks for a `*.html.html` template along with a plain text `*.text.html` template. From djmail's [code](https://github.com/bameda/djmail/blob/297c7a8c343ab5f4b1a8ea50168e2f9638d88722/djmail/template_mail.py#L85) there seems to be no way to disable sending of HTML emails.

Possible solutions include:

* Do nothing, it's only a warning in the logs, not a stack trace. Can be annoying because it pollutes our logs.
* Provide a `*.html.html` template, even if we fill it with plain text ? For what it's worth `djmail` [seems to be doing the right thing](https://github.com/bameda/djmail/blob/297c7a8c343ab5f4b1a8ea50168e2f9638d88722/djmail/template_mail.py#L101), providing both plain text and html as an alternative in the same email.

**Comment by zopieux** [comment]
Yes, this is a super old warning that I've elect to ignore because asking to provide blank files, instead of just no file at all, is a really poor API choice from djmail. I'd prefer djmail to support not providing some files. I wouldn't care too much about polluting logs. What you can do if you really care, is to blackhole djmail warnings, or maybe this one in particular if this can be expressed using  [Django/Python logging filtering](https://docs.djangoproject.com/en/2.2/topics/logging/#examples).

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/227
