### ISSUE TITLE
admin/schools/school/ does not display the correct number of contestants

### ISSUE THREAD

**Issue by cyril-amar** [prologin/concours-site#286]
On the admin/schools/school/ page, the column Candidats displays the same values as Candidats pour l'édition en cours instead of the total number.

**Comment by TheoHollender** [comment]
So the problem comes from the annotations list in the SchoolAdmin class, it seems like django is doing both of the modification on the queryset on the same queryset leading to the last queryset being the one which will have the final values so if we invert cecc and tcc, the cecc will have the tcc value.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/286
