### ISSUE TITLE
forum : add a way to be notified when a new message is posted on a thread you participated in

### ISSUE THREAD

**Issue by Elfikurr** [prologin/concours-site#294]
I know that #81 shows us whether we read all the thread's messages, but if we do not go on the forum, we have no way of knowing if a new message was posted.

Has it already been discussed ?

**Comment by seirl** [comment]
I don't know if it's been discussed, but it's a good feature. +1

**Comment by TheoHollender** [comment]
So to do that i have an idea:
Creating a ThreadSubscribed model which contains a thread and an username or include this directly in the ReadState model by adding a boolean,
And so that the server does not have to recalculate each time the notifications, that there is a Notification model that contains every notifications and is modified when the latest post is more recent as the actual stored post. 
Is this a good way of doing it or do you have any suggestions?

**Comment by TheoHollender** [comment]
And also little question, are the commits of #81 applyed to the branches or do i need to pull it into my dev environment?

**Comment by TheoHollender** [comment]
So that we could have a page on which all notifications are placed

**Comment by TheoHollender** [comment]
So there are 3 possiblities : 
1. We add the notification system in the post above and you can subscribe to every thread and you have a page of notifications
2. We add a mail system that sends you a mail by saying that someone answered to the thread and a link to the thread
3. We add both of them and the subscribe button could be like the youtube one, you choose to have notifications by mail or on the page.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/294
