### ISSUE TITLE
Challenge mode with import/export

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#53]
> ###### Originally posted 2016-01-16 18:49 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-25 18:42 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Mostly done as of daf5527.

**Comment by seirl** [comment]
> ###### Originally posted 2016-01-27 01:28 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Problems encountered:

- default DB is not sqlite3
- RECAPTCHA_KEY has to be set to a dummy value
- The problem is always display_website: false but should be displayed for normal users anyway.

TODO:

- Export in the documents module
- Import the data with an upload form somewhere in the website?

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-27 08:55 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

* Did you use a `semifinal` setting file? That is, a setting file that `import`s from `semifinal_common`?
* What's the point of having a web import? Setting up the semifinal website is a one-off procedure that includes creating the database (which is command line) so I don't see any value doing the import on the running website. Hell, you can't actually have a running website before you have any edition/event because there is a middleware that needs this stuff. I don't want to create special cases everywhere just for the "database empty, before the import" state, which will exist for like 10 seconds.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-27 20:07 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Problems encountered:

* ~~default DB is not sqlite3~~
* ~~RECAPTCHA_KEY has to be set to a dummy value~~
* ~~The problem is always display_website: false but should be displayed for normal users anyway.~~

TODO:

* ~~Export in the documents module~~

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-27 20:08 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Mostly done as cd56802. Keeping open because it is still missing the importing of semifinal data back to production.

**Comment by seirl** [comment]
> ###### Originally posted 2016-01-27 20:12 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Just thought about something else missing: we should figure out what we do for the languages documentation too.

A quick solution could be to reuse this:

https://bitbucket.org/prologin/oldsite/src/master/docs/prepare_conf.sh?at=master&fileviewer=file-view-default

served with nginx with an autoindex?

This script needs to be updated and require less human interaction (java...)

**Comment by zopieux** [comment]
> ###### Originally posted 2016-03-04 17:05 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Web import done in 0b22cba.

@seirl for the documentation please refer to https://github.com/prologin/envlive/issues/8
