### ISSUE TITLE
Usernames across an event (semifinal, final) are not guaranteed to be unique

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#99]

**Comment by seirl** [comment]
Completely overengineered solution:

- Add a table "NormalizedUsernames" which contains a string (the normalized username) and an integer (the next available ID, default 0)
- Add a text field "normalized_username" in the user table
- Override the save() function so that every time an user is saved, if its first name or last name was changed, we get a new normalized_username and change the field value

**Comment by zopieux** [comment]
What about no.

**Comment by seirl** [comment]
Better solution: do like for passwords, `user.normalized_username_for(event)`

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/99
